version: '2.1'
services:

  zookeeper:
    image: debezium/zookeeper:latest
    restart: unless-stopped
    healthcheck:
      test: echo stat | nc localhost 2181
      interval: 10s
      timeout: 10s
      retries: 3
    ports:
      - "2181:2181/tcp"
      - "2888:2181/tcp"
      - "3888:3888/tcp"

  kafka:
    image: debezium/kafka:latest
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "bash", "-c", "unset" , "JMX_PORT" ,";" ,"kafka-topics.sh","--zookeeper","zookeeper:2181","--list"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "9092:9092/tcp"
    links:
     - zookeeper

  mysqldb:
    image: debezium/example-mysql:latest
    mem_limit: 1073741824
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hmysqldb", "-uroot", "-ppassword", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "3306/tcp"
    environment:
      MYSQL_ROOT_PASSWORD: debezium
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw

  connect:
    image: debezium/connect:latest
    command: sh ./setup_connect.sh
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-hmysqldb", "-uroot", "-ppassword", "--silent"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "8083:8083"
    environment:
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      links:
         -mysqldb
         -kafka
         -zookeeper

