version: '2.2'
services:
  zookeeper:
    image: debezium/zookeeper:latest
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:latest
    ports:
     - 9092:9092
    links:
     - zookeeper
    volumes:
      - 'kafka_data:/data'
      - 'kafka_config:/config'
      - 'kafka_logs:/logs'
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: debezium/example-mysql:latest
    ports:
     - 3306:3306
    environment:
     - MYSQL_ROOT_PASSWORD=debezium
     - MYSQL_USER=mysqluser
     - MYSQL_PASSWORD=mysqlpw
  connect:
    image: ddebezium/connect:latest
    ports:
     - 8083:8083
     - 5005:5005
    links:
     - zookeeper
     - kafka
     - mysql
    environment:
     - BOOTSTRAP_SERVERS=kafka:9092
     - GROUP_ID=1
     - CONFIG_STORAGE_TOPIC=my_connect_configs
     - OFFSET_STORAGE_TOPIC=my_connect_offsets
 volumes:
    kafka_data:
        driver: host
        driver_opts:
            source: /tmp/kafka/data
    kafka_config:
        driver: host
        driver_opts:
            source: /tmp/kafka/config
    kafka_logs:
        driver: host
        driver_opts:
            source: /tmp/kafka/logs
